"""New default base

Revision ID: b753dc26d4eb
Revises: acd93d4ecb2f
Create Date: 2022-06-06 10:46:01.575605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b753dc26d4eb'
down_revision = 'acd93d4ecb2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('items', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('todos', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('todos', 'updated_at')
    op.drop_column('todos', 'created_at')
    op.drop_column('items', 'updated_at')
    op.drop_column('items', 'created_at')
    # ### end Alembic commands ###
